### ISSUE TITLE
Error parsing glacis from dict.org, internal state?

### ISSUE THREAD

**Issue by SevereOverfl0w** [jams2/py-dict-client#1]
After getting the definition for "glacis" the following definition will fail, no matter what it is:

```
Python 3.8.5 (default, Aug 11 2020, 13:06:53) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dictionary_client import DictionaryClient
>>> dc = DictionaryClient('dict.org')
>>> dc.define('glacis')
<dictionary_client.response.DefineWordResponse object at 0x7f8fee2c2b50>
>>> dc.define('word')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/overfl0w/workshop/kindle-to-anki/env/lib/python3.8/site-packages/dictionary_client/dictionary_client.py", line 116, in define
    return self._get_response(define_word_command(word, db), DefineWordResponse)
  File "/home/overfl0w/workshop/kindle-to-anki/env/lib/python3.8/site-packages/dictionary_client/dictionary_client.py", line 97, in _get_response
    return response_class(self._recv_all())
  File "/home/overfl0w/workshop/kindle-to-anki/env/lib/python3.8/site-packages/dictionary_client/dictionary_client.py", line 52, in _recv_all
    status_code = self._get_status(bytes_received)
  File "/home/overfl0w/workshop/kindle-to-anki/env/lib/python3.8/site-packages/dictionary_client/dictionary_client.py", line 80, in _get_status
    return int(response_bytes[:3])
ValueError: invalid literal for int() with base 10: b'00r'
```

Thanks for the great library!

**Comment by jams2** [comment]
Hi,

glad someone else has found the library useful. At the time of building I had only tested this against a local server, and wasn't aware that there were public online servers, so that's cool.

I'll look into it.

**Comment by jams2** [comment]
@SevereOverfl0w,
I've merged a change that should resolve your issue, the update has been pushed to pypi.
Thanks for raising, I haven't looked at this code for a while and there are a number of improvements to be made.

**Comment by SevereOverfl0w** [comment]
That worked great, thanks!
